# This file was generated by GoReleaser. DO NOT EDIT.
cask "ironstate" do
  version "0.4.3"

  on_macos do
    on_arm do
      sha256 "1b1bf96372e77b88bf0a9fc32efae5d733a9f66c6752cf67e496a37408d3cf5d"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "746ae3b7b039c3de4fc756e53a87467523981ddc5a3a1344156e56d00c96a2d7"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "084b6efa7ba1af11d5b436046c7e55a04427e1debaacd763c15ed21ebd3d687c"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3eceeb23dd7c76e5ae155dde27b638f472029937be4bf066c0921e956a87be7d"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ironstate"
  desc "ironstate is a declarative, Ansible-style task runner driven by YAML."
  homepage "https://github.com/TacoContent/ironstate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ironstate"
  manpage "ironstate.1"

  generate_completions_from_executable "ironstate", "completion",
    base_name: "ironstate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
