# This file was generated by GoReleaser. DO NOT EDIT.
cask "ironstate" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "8bc844498081e971a3243617a11cc65f372309665b3f67b8e2be6319c21026dc"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5dcdb8c2a34f7ef7ad61ea9b657d276f153db62e7e72f7f1db23281f23576ede"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0676852679ce9cd3bea8a6fbd147334c69ca308603ed2ae54c1a806c3d2e2044"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf69e0fa77066064f9fac1de2fc8fdea044fba5eaf856e20587b9512bb79e5b9"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ironstate"
  desc "ironstate is a declarative, Ansible-style task runner driven by YAML."
  homepage "https://github.com/TacoContent/ironstate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ironstate"
  manpage "ironstate.1"

  generate_completions_from_executable "ironstate", "completion",
    base_name: "ironstate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
