# This file was generated by GoReleaser. DO NOT EDIT.
cask "ironstate" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "46a6b2c0edc2ab3d7a41d2e04c2b000160d764b356344a173080570f45638e67"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "22b87b510edda4fc78030be73701911ca6896b742347fdf82eaa3820dbe9bc39"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c2905179032af111b869e9a11c21145d19edf3306054791e00764070cf21de45"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "79cf7e64a220a43969b144c14755e19f6ccc5dbcaafbd83b9a273ae722ef4425"
      url "https://github.com/TacoContent/ironstate/releases/download/v#{version}/ironstate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ironstate"
  desc "ironstate is a declarative, Ansible-style task runner driven by YAML."
  homepage "https://github.com/TacoContent/ironstate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ironstate"
  manpage "ironstate.1"

  generate_completions_from_executable "ironstate", "completion",
    base_name: "ironstate",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
