# This file was generated by GoReleaser. DO NOT EDIT.
cask "xget" do
  version "2.0.1"

  on_macos do
    on_arm do
      sha256 "5a660d19a25d77f827a5398c089b96e7b0594c6f773d57340279d0c93f9b6f0e"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e561cd9257c040e11b5c8587dfad1fc751beb6e1b766659fae6d20a08f963023"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ccd7506b1074e2860551fd4ac070a9c3dd98e676bfb58ee31c82b23e2ecab5f7"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5cb9421c19cede83b0e28276a3c1b87f51a955b870b8d90157acc96647d1da77"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_linux_amd64.tar.gz"
    end
  end

  name "xget"
  desc "xget is a tool for downloading binaries from the GitHub releases."
  homepage "https://github.com/camalot/xget"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xget"
  manpage "xget.1"

  generate_completions_from_executable "xget", "completion",
    base_name: "xget",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
