# This file was generated by GoReleaser. DO NOT EDIT.
cask "xget" do
  version "2.5.0"

  on_macos do
    on_arm do
      sha256 "81bd02fc8c4ca94e9a5c5cbddaf9d1b0f91d348c95c2ce784e8eb0495dc00228"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b852dcfeffe0f5d918223fbdd504296090b3a11b7aa5bce3e989ecffbd010b5"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c4cc7b6936e56f63c43a98f917386811ef78d0ed486038c13310b4c07c22a28d"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b323ed41e17f067df790b7cb8b906586110d5779869465bcb99032a87615e4ee"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_linux_amd64.tar.gz"
    end
  end

  name "xget"
  desc "xget is a tool for downloading binaries from the GitHub releases."
  homepage "https://github.com/camalot/xget"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xget"
  manpage "xget.1"

  generate_completions_from_executable "xget", "completion",
    base_name: "xget",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
