# This file was generated by GoReleaser. DO NOT EDIT.
cask "xget" do
  version "2.1.2"

  on_macos do
    on_arm do
      sha256 "263829b5debc614134117bae0666c385c793a7c8448cc71eceefdb03864776eb"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1ef200be27a4f249538614c8da6204490dc2b7a2cc1ad0b5ef85adad55403f5b"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "53479f57961feda18a71f5ab48b8dbaea88bdd318048e59af017d6b15172f34b"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "96792edad1d181c6a1fee242c91d96a7e168efde135e0b2dd000cfc91475a949"
      url "https://github.com/camalot/xget/releases/download/v#{version}/xget_#{version}_linux_amd64.tar.gz"
    end
  end

  name "xget"
  desc "xget is a tool for downloading binaries from the GitHub releases."
  homepage "https://github.com/camalot/xget"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xget"
  manpage "xget.1"

  generate_completions_from_executable "xget", "completion",
    base_name: "xget",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
