---
name: Homebrew CI

on:
  push:
    branches:
      - main
    paths:
      - 'Casks/**'
  workflow_dispatch:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - shell: bash
        id: scoops
        run: |
          echo "::group::Collecting scoop apps"
          apps='[]'
          for file in Casks/**/*.rb; do
            echo "Processing $file"
            name="$(basename "${file%.rb}")"
            description=$(grep -Po 'desc\s+"?\K[^"]+' "$file")
            version=$(grep -Po 'version\s+"?\K[^"]+' "$file")
            license=$(grep -Po 'license\s+"?\K[^"]+' "$file")
            homepage=$(grep -Po 'homepage\s+"?\K[^"]+' "$file")

            apps=$(echo "$apps" | jq --arg name "$name" --arg description "$description" --arg version "$version" --arg license "$license" --arg homepage "$homepage" \
              'if any(.[]; .name == $name) then
                map(if .name == $name then .description = $description | .version = $version | .license = $license | .homepage = $homepage else . end)
              else
                . + [{name: $name, description: $description, version: $version, license: $license, homepage: $homepage}]
              end')
          done
          # update the apps array with the extracted metadata

          apps=$(echo "$apps" | jq -c '.')
          echo "$apps" | jq '{apps: .}' > "$RUNNER_TEMP/.apps-data.json"
          echo "::endgroup::"

      - uses: cuchi/jinja2-action@v1.3.0
        with:
          template: .github/templates/homebrew.j2
          output_file: HOMEBREW.md
          data_file: ${{ runner.temp }}/.apps-data.json
          data_format: json
        env:
          ORG: '${{ github.repository_owner }}'
          REPO: '${{ github.event.repository.name }}'

      - name: Commit updated HOMEBREW.md
        run: |
          gh auth setup-git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add HOMEBREW.md
          git commit -m "Update HOMEBREW.md" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"
        env:
          GH_TOKEN: ${{ github.token }}